### ISSUE TITLE
`sharpen-progress-dial` calculation is wrong?

### ISSUE THREAD

**Issue by mohd-anas-ansari** [coggen/kezuri#20]
<img width="198" alt="Screenshot 2023-12-22 at 4 51 00 PM" src="https://github.com/coggen/kezuri/assets/25636554/e684a6ea-8587-49b4-9f5f-e5a572a4e553">

**Comment by jabbett** [comment]
I will update the image to fill the loop with red for high risk.

**Comment by jabbett** [comment]
here's the complete set:
![image](https://github.com/coggen/kezuri/assets/923971/ab12c76c-aed8-4f7e-9e9c-971bf3fd71a9)
