### ISSUE TITLE
`sharpen-profile-card`s don't have same dimensions for longer names.

### ISSUE THREAD

**Issue by mohd-anas-ansari** [coggen/kezuri#21]
<img width="1728" alt="Screenshot 2024-01-08 at 4 36 17 PM" src="https://github.com/coggen/kezuri/assets/25636554/a2b35558-3083-49f1-a2bf-5df320191e27">

**Comment by jabbett** [comment]
Recreated in Storybook:
<img width="983" alt="image" src="https://github.com/coggen/kezuri/assets/923971/eba7a894-0f1b-4229-a4a5-0b1a998eb518">

**Comment by jabbett** [comment]
And fixed to look like this:
<img width="988" alt="image" src="https://github.com/coggen/kezuri/assets/923971/230adf1e-83f4-4d31-8fb5-58dec53b81c0">

using a structure like

```
<div class="row row-cols-lg-4 row-cols-xl-6">
  <div class="col">
    <sharpen-profile-card ...></sharpen-profile-card>
  </div>
  <div class="col">
    <sharpen-profile-card ...></sharpen-profile-card>
  </div>
  <div class="col">
    <sharpen-profile-card ...></sharpen-profile-card>
  </div>
  <div class="col">
    <sharpen-profile-card ...></sharpen-profile-card>
  </div>
</div>
```
