### ISSUE TITLE
`info-block` in Kezuri.

### ISSUE THREAD

**Issue by mohd-anas-ansari** [coggen/kezuri#22]
Need a notice block for information and notices.

`info-block` in SWC:
https://github.com/coggen/sharpen-web-components/tree/main/src/components/info-block

<img width="849" alt="image" src="https://github.com/coggen/kezuri/assets/25636554/7dd90480-ad23-4663-bca4-378b57ed4cd0">

**Comment by jabbett** [comment]
Hi @mohd-anas-ansari! Should be doable with the sharpen-alert. I used Storybook to demo the content you're looking for:

![image](https://github.com/coggen/kezuri/assets/923971/385f8df1-fbf8-493b-bd45-957e2c107dd1)

```
<sharpen-alert type="warning" icon="info">After continuing, you will not be able to change...</sharpen-alert>
```

**Comment by mohd-anas-ansari** [comment]
Thanks, @jabbett  I just remembered we have `sharpen-alert`. Sorry for the confusion.

**Comment by jabbett** [comment]
No worries! (I have updated documentation for alerts that'll go out in the next release which better shows how they're configurable for different scenarios.)
