### ISSUE TITLE
`color` and `background-color` support for `<sharpen-profile-card>` 

### ISSUE THREAD

**Issue by deepakmahakale** [coggen/kezuri#8]
Currently, we display the records/ profiles with different colors.

![image](https://github.com/coggen/kezuri/assets/14993828/29313202-4faf-49ec-ae8b-805f67cd9466)

This is how we currently apply color.
 
<img width="740" alt="Screenshot 2023-11-29 at 17 30 00" src="https://github.com/coggen/kezuri/assets/14993828/06546f82-e4fa-4e3c-be0d-df39b8011b1c">

**Comment by jabbett** [comment]
![image](https://github.com/coggen/kezuri/assets/923971/4be2c588-db10-43dd-bb11-33823cf1dca7)
