### ISSUE TITLE
<sharpen-alert> heading style not working as expected in sharpen 

### ISSUE THREAD

**Issue by deepakmahakale** [coggen/kezuri#9]
Expected vs Actual

<img width="833" alt="Screenshot 2023-11-30 at 18 50 04" src="https://github.com/coggen/kezuri/assets/14993828/f8ddc470-2deb-4576-b2af-a9c0cec91713">

```html
<sharpen-alert type="warning" icon="warning" heading="Action Needed">
  <p>Please complete Gunther's profile by filling in the Date of Birth, the Kindergarten Start Year, and Opting in or out of the Sharpen Research Program.</p>
</sharpen-alert>
```

PS. ignore the icon we can change that with alert but the heading style

**Comment by jabbett** [comment]
@deepakmahakale We don't see this in Storybook, so you probably have another style definition from outside Kezuri that's cascading and styling this text. When you inspect the "Action Needed" element, what are all the styles that get listed?

**Comment by jabbett** [comment]
Out of the box, it should look quite close to the original:
![image](https://github.com/coggen/kezuri/assets/923971/9e6bbbf3-729b-4a6e-a9f0-fe8d8321be3b)

I'll close this as invalid but we can open a new issue if we notice problems after removing Craft.
